// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Person struct {
	ID        string `json:"id"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Age       int    `json:"age"`
	Email     string `json:"email"`
}

type PersonInput struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Age       int    `json:"age"`
	Email     string `json:"email"`
}

type Query struct {
}

type Video struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	URL         string  `json:"url"`
	Author      *Person `json:"author,omitempty"`
	Description string  `json:"description"`
}

type VideoInput struct {
	Title       string       `json:"title"`
	URL         string       `json:"url"`
	Description string       `json:"description"`
	Author      *PersonInput `json:"author"`
}
